### ISSUE TITLE
Add basic layout and files 

### ISSUE THREAD

**Issue by rom1504** [LAION-AI/laion5B-paper#1]

**Comment by robvanvolt** [comment]
Has anyone started an overleaf / latex project yet?

> Formatting instructions:  All submissions must be in PDF format. Submissions are limited to nine content pages, including all figures and tables; additional pages containing the NeurIPS paper checklist and references are allowed.  The page limit was increased to ensure that authors have space to address the checklist questions. You must format your submission using the [NeurIPS 2022 LaTeX style file](https://neurips.cc/Conferences/2022/PaperInformation/StyleFiles) which includes a “preprint” option for non-anonymous preprints posted online. The maximum file size for submissions is 50MB. Submissions that violate the NeurIPS style (e.g., by decreasing margins or font sizes) or page limits may be rejected without further review. If your submission is accepted, you will be allowed an additional content page for the camera-ready version. Papers may be rejected without consideration of their merits if they fail to meet the submission requirements, as described in this document.

https://neurips.cc/public/guides/PaperChecklist
https://nips.cc/Conferences/2022/CallForPapers

An alternative that Ludwig suggested:
https://neurips.cc/Conferences/2022/CallForDatasetsBenchmarks

**Comment by rom1504** [comment]
I think @Zasder3 has started something.
Let's commit a version version soon indeed.

**Comment by robvanvolt** [comment]
Done (https://www.overleaf.com/project/6269fb5a48a63539152e9045)
